### PR TITLE
Carthage Framework, Podspec

### PR DESCRIPTION
**Pull request by flovilmart**
- Adds dynamic framework for Carthage support
- Adds pod spec

### CODE REVIEW

**Comment by mikeash** [comment]
I'm happy to add a framework target to the project if that's helpful, but I don't want to litter the repository with support files for specific package distribution systems (surely whatever data they need can and should be stored on their end, not mine) and definitely don't want to add binary artifacts.

**Comment by flovilmart** [comment]
@mikeash what do you mean by that? The Podfile? or the Framework target?

**Comment by mikeash** [comment]
A framework target is fine, but no podspec or Carthage directory or built .framework within. I don't see the need for xcconfig files either, seems like all that info could just reside within the normal build settings.

**Comment by flovilmart** [comment]
Alright. I'm not sure the cocoapods compatibility will be maintained without the Podspec.

**Comment by mikeash** [comment]
Well, I have nothing against Cocoapods in general, but if they can't include this project without stuff in my repository specific to their system, well, their loss.

**Comment by flovilmart** [comment]
Alright! 

I'll make the update.

**Comment by flovilmart** [comment]
Updated, let me know :)

**Comment by mikeash** [comment]
Great, thanks! Looks pretty good. Are there any important changes in main.m? Looks like just a bunch of indentation changes, which I'll revert, but I want to make sure I didn't miss anything.

Are `MACollectionUtilitiesVersionNumber` and `MACollectionUtilitiesVersionString` used for anything? I assume this is related to Carthage somehow, but without an actual definition of the variables they look like they're useless. But I don't want to unilaterally delete them without being sure!

I think that's it. I can make those changes when merging, once you confirm I'm not screwing it up somehow.

**Comment by flovilmart** [comment]
The version numbers are generated by Xcode when creating the target, I believe they can be removed.




Otherwise for the the main, I haven't added any test to it.

**Comment by mikeash** [comment]
Thanks. I went ahead and removed those changes and merged in the rest. Seems to work! Let me know if I messed anything up.

**Comment by flovilmart** [comment]
Sounds good! Thanks!

**Pull request closed without merging**
